### ISSUE TITLE
Electron.NET Integration

### ISSUE THREAD

**Issue by symbiogenesis** [riganti/dotvvm-electron#1] opened 2017-11-03 16:33 UTC
Would it be worthwhile to use Electron.NET for all the Electron bindings, to prevent re-inventing the wheel? I could imagine this allowing better support for new versions, more configurability, etc.

https://github.com/ElectronNET/Electron.NET

**Comment by tomasherceg** [comment] 2017-11-04 11:07
Yep, we have found this project few days after we finished our own solution. 

@adamjez was researching about how they are doing the .NET to Electron communication. Adam, can you share some details here?

**Comment by adamjez** [comment] 2017-11-04 23:19
Their solution is very similar to ours, except that they have implemented a lot more electron API. They use Socket.IO to communicate between .NET and Electron (we are currently using raw websockets). 

+ **I like** that they build CLI tool which helps with creating an electron version of a web application.

+ **I don't like** that they are using static properties all around a code instead of DI (eg. [ShellController](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.WebApp/Controllers/ShellController.cs)). Their implementation of electron events is as bad as ours. Maybe theirs is even worse because they can't _preventDefault_ any event. We got a prototype of subscribing to events per page which I think is handy feature.

But the most important think is, that their repository is **incomparably more active than ours**. In the near future there will be probably many contributors (currently the repository has **805 stars**).

**Comment by engineers-tools** [comment] 2017-12-25 09:58
Have you guys given this any more thought? I'm looking for a cross-platform development stack the Electron.NET and DotVVM seem like a very good choice.
I've just tried a new example project using latest versions, but there seems to be some issues around the DotVVM router when embedded in an Electron.NET app.

**Comment by tomasherceg** [comment] 2017-12-25 10:15
Can you describe the issues in a detail? I have several working Electron apps in DotVVM.

**Comment by engineers-tools** [comment] 2017-12-25 10:25
Hi Tomas. Thanks for your prompt reply. First of all, great product. I really like it. Just heard your second podcast with .NET Rocks and I'm trying it right now.

Anyway, the steps that I've followed are:

* Created DotVVM project using the DotVVM Web App (.NET Core) project template.
* Add the ElectronNET.API Nuget package to the project.
* Add the `<DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />` instruction to the project file.
* Run `dotnet restore`
* Run `dotnet electronize init`
* Run `dotnet electronize start`

In this case, the application hangs without opening Electron. I then go to the /bin/Debug/netcoreapp2.0/win-x64/ directory and run the executable from there.

On the command prompt I get an error that says that the AutoDiscoveryRoutes function could not find a Views directory.

It seems that during development, the webapp gets created in a different folder under the "obj" directory and my guess is that this is what's causing the error. I'm trying to find a configuration option to correct this, but no luck so far.

**Comment by exyi** [comment] 2017-12-25 10:27
On Mon, 2017-12-25 at 09:58 +0000, Engineers Tools wrote:
> Have you guys give this any more thought? I'm looking for a cross-
> platform development stack the Electron.NET and DotVVM seem like a
> very good choice.

To be honest, I don't think that electron+dotvvm gives you many
advantages in comparison with a dotvvm website. It depends on what type
of application are you trying to create, but IMO either electron or
dotvvm will make your life harder than it has to be. I'd rather
reconsider either building a (dotvvm) web app (without electron, with a
webserver) or normal .NET UI application (try AvaloniaUI for XPlat)

> I've just tried a new example project using latest versions, but
> there seems to be some issues around the DotVVM router when embedded
> in an Electron.NET app.

But this seems like a bug that should be fixed, could you be more
specific about "some issues"?

**Comment by engineers-tools** [comment] 2017-12-25 10:32
Hi exyi.

I'm trying to find a platform that would allow me to build simple open-source Desktop engineering applications. It'd be great if I could deploy the programs in any platform. I think I'd reach a wider audience.

So far I've tried a few things with Electron, but I'm more comfortable in C# than I am with JS for my business logic.

**Comment by tomasherceg** [comment] 2017-12-26 11:50
Can you paste your CSPROJ here? I think the problem is that the Views folder is not copied during publish.

**Comment by engineers-tools** [comment] 2017-12-27 03:29
The structure of the CSPROJ is as follows.
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <!--Include Views-->
    <Content Include="**/*.dothtml" Exclude="obj/**/*.*;bin/**/*.*">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <!--Include MasterPage Views-->
    <Content Include="**/*.dotmaster" Exclude="obj/**/*.*;bin/**/*.*">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <!--Include Custom Control Views-->
    <Content Include="**/*.dotcontrol" Exclude="obj/**/*.*;bin/**/*.*">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Remove="dotvvm_serialized_config.json.tmp" />
    <None Remove="Views\MasterPage.dotmaster" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="0.0.7" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="DotVVM.AspNetCore" Version="1.1.7" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="DotVVM.Compiler.Light" Version="1.1.7" />
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

```
However, I found out that the application runs properly in Electron when I remove the following instruction from the `Startup.cs` that comes with the project template.

```
// use static files
 app.UseStaticFiles(new StaticFileOptions
 {
     FileProvider = new PhysicalFileProvider(env.WebRootPath)
 });
```

**Comment by tomasherceg** [comment] 2017-12-27 09:27
Oh, the `wwwroot` folder was a problem. If it is empty, it doesn't get created in the publish directory, and the static files middleware crashes because it cannot find it.

**Comment by engineers-tools** [comment] 2017-12-27 09:40
That makes sense.  Thank you for the time you took to look into this. 
I'm up and running now.  I'll start with the first application I have in mind using this stack.

**Comment by tomasherceg** [comment] 2017-12-27 09:46
Awesome, should you need any help, let us know here or on our [Gitter](https://gitter.im/riganti/dotvvm).

**Closed as completed by tomasherceg** 2017-12-27 09:46 UTC
